name: validate
on: [push, pull_request]
jobs:
  rawhide:
    runs-on: ubuntu-latest
    container:
      image: docker.io/fedora:rawhide
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: install test dependencies
        run: dnf install -y python3-pylint python3-gobject-base make

      - name: run tests
        run: make ci
